config/routes.rb
Santhoshonet::Application.routes.draw do

  resources :aims
  resources :blogs
  resources :contributors
  resources :categories
  resources :mail_credentials

  get "db/reset"
  get 'home/index'

  match "/" , :controller => "home", :action => "index"
  match "/contact" , :controller => "home", :action => "contact"
  match "/aboutme" , :controller => "home", :action => "aboutme"
  match "/opensources" , :controller => "home", :action => "opensources"
  match "/blog/:id/:title", :controller => "blogs", :action => "show"
  match "/category/:category", :controller => "blogs", :action => "category_wise"
  match ":controller/:action"


end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :category
  belongs_to :contributor
  validates_presence_of :title,  :categories_id , :content,  :contributors_id
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
         before_filter :load_categories, :aim
  # GET /blogs
  # GET /blogs.xml
  def index
           
           
    @blogs = Blog.order("id desc").all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])
    render :layout => "application"
  end

  # displaying category wise
  def category_wise
    category_name = params[:category]
    unless category_name.nil?
      category = Category.find_by_name(category_name)
      unless category.nil?
        @blogs = Blog.find_all_by_categories_id(category.id)
        render :'home/index' , :layout => "application"
      end
    end
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
    @blog = Blog.new(params[:blog])
    contributor = Contributor.find(1)
    @blog.contributors_id = contributor.id
    @blog.contributor = contributor
    category = Category.find(params[:name][:category_id])
    @blog.categories_id = category.id
    @blog.category = category
    respond_to do |format|
      if @blog.save
        format.html { redirect_to(@blog, :notice => 'Blog was successfully created.') }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    @blog = Blog.find(params[:id])
    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(@blog, :notice => 'Blog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to(blogs_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <p>
        <% @blog.errors.full_messages.each do |msg| %>
            <%= msg %> </br>
        <% end %>
    </p>
  <% end %>
    <fieldset>
        <p><%= f.label :title %></p>
        <p><%= f.text_field :title %></p>
        <p><label>Category</label></p>
        <p><%= collection_select(:name,:category_id,@categories,:id, :name, {:prompt => true})  %></p>
        <p><%= f.label :content %></p>
        <p class="big-textarea"><%= f.text_area :content %></p>
        <p><%= f.submit %></p>
    </fieldset>
<% end %>

app/views/blogs/edit.html.erb
<div class="two-thirds">
    <h1>Editing blog</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @blog %> |
</div>
<%=  javascript_include_tag "ckeditor" %>
<%=  stylesheet_link_tag "contents" %>
<script type="text/javascript" language="JavaScript">
    CKEDITOR.replace( 'blog_content',
    	{
    		extraPlugins : 'autogrow',
    		removePlugins : 'resize'
    	});
</script>

app/views/blogs/index.html.erb
<div class="two-thirds">
    <h1>Listing blogs</h1>
    <table>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <% @blogs.each do |blog| %>
            <tr>
                <td><%= blog.title %></td>
                <td><%= blog.content %></td>
                <td><%= link_to 'Show', blog %></td>
                <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
                <td><%= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
        <% end %>
    </table>
    <br />
    <%= link_to 'New Blog', new_blog_path %>
</div>

app/views/blogs/new.html.erb
<div class="two-thirds">
    <h1>Add new note</h1>
    <%= render 'form' %>
</div>
<%=  javascript_include_tag "ckeditor" %>
<%=  stylesheet_link_tag "contents" %>
<script type="text/javascript" language="JavaScript">
    CKEDITOR.replace( 'blog_content',
    	{
    		extraPlugins : 'autogrow',
    		removePlugins : 'resize'
    	});
</script>

app/views/blogs/show.html.erb
<div class="two-thirds">
    <p id="notice"><%= notice %></p>
    <div class="post">
	    <div class="post-meta">
            <h1><a href="#"><%= @blog.title %></a></h1>
            <small><%= @blog.updated_at.strftime("%b %d, %Y") %></small>
            <% contributor = nil
                unless @blog.contributors_id.nil? then contributor = Contributor.find(@blog.contributors_id) end %>
			<small>by <a href="#"><%= if contributor.nil? then "" else contributor.username end %></a></small>
            <% category = nil
                unless @blog.categories_id.nil? then category = Category.find(@blog.categories_id) end %>
			<small>in <a href="#"><%= if category.nil? then "" else category.name end %></a></small>
		</div>
        <p>
          <%= @blog.content.html_safe %>
        </p>
	</div><!--post ends-->
    <%=  render :partial => 'partials/commentSystem' %>
</div>