config/routes.rb
Santhoshonet::Application.routes.draw do

  resources :aims
  resources :blogs
  resources :contributors
  resources :categories
  resources :mail_credentials

  get "db/reset"
  get 'home/index'

  match "/" , :controller => "home", :action => "index"
  match "/contact" , :controller => "home", :action => "contact"
  match "/aboutme" , :controller => "home", :action => "aboutme"
  match "/opensources" , :controller => "home", :action => "opensources"
  match "/blog/:id/:title", :controller => "blogs", :action => "show"
  match "/category/:category", :controller => "blogs", :action => "category_wise"
  match ":controller/:action"


end

app/models/aim.rb
class Aim < ActiveRecord::Base
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController
  # GET /aims
  # GET /aims.xml
  def index
    @aims = Aim.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aims }
    end
  end

  # GET /aims/1
  # GET /aims/1.xml
  def show
    @aim = Aim.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @aim }
    end
  end

  # GET /aims/new
  # GET /aims/new.xml
  def new
    @aim = Aim.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aim }
    end
  end

  # GET /aims/1/edit
  def edit
    @aim = Aim.find(params[:id])
  end

  # POST /aims
  # POST /aims.xml
  def create
    @aim = Aim.new(params[:aim])

    respond_to do |format|
      if @aim.save
        format.html { redirect_to(@aim, :notice => 'Aim was successfully created.') }
        format.xml  { render :xml => @aim, :status => :created, :location => @aim }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aim.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aims/1
  # PUT /aims/1.xml
  def update
    @aim = Aim.find(params[:id])

    respond_to do |format|
      if @aim.update_attributes(params[:aim])
        format.html { redirect_to(@aim, :notice => 'Aim was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aim.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aims/1
  # DELETE /aims/1.xml
  def destroy
    @aim = Aim.find(params[:id])
    @aim.destroy

    respond_to do |format|
      format.html { redirect_to(aims_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/views/aims/_form.html.erb
<%= form_for(@aim) do |f| %>
  <% if @aim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aim.errors.count, "error") %> prohibited this aim from being saved:</h2>

      <ul>
      <% @aim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aims/edit.html.erb
<h1>Editing aim</h1>

<%= render 'form' %>

<%= link_to 'Show', @aim %> |
<%= link_to 'Back', aims_path %>

app/views/aims/index.html.erb
<h1>Listing aims</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aims.each do |aim| %>
  <tr>
    <td><%= aim.title %></td>
    <td><%= link_to 'Show', aim %></td>
    <td><%= link_to 'Edit', edit_aim_path(aim) %></td>
    <td><%= link_to 'Destroy', aim, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aim', new_aim_path %>

app/views/aims/new.html.erb
<h1>New aim</h1>

<%= render 'form' %>

<%= link_to 'Back', aims_path %>

app/views/aims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @aim.title %>
</p>


<%= link_to 'Edit', edit_aim_path(@aim) %> |
<%= link_to 'Back', aims_path %>