config/routes.rb
Santhoshonet::Application.routes.draw do

  resources :aims
  resources :blogs
  resources :contributors
  resources :categories
  resources :mail_credentials

  get "db/reset"
  get 'home/index'

  match "/" , :controller => "home", :action => "index"
  match "/contact" , :controller => "home", :action => "contact"
  match "/aboutme" , :controller => "home", :action => "aboutme"
  match "/opensources" , :controller => "home", :action => "opensources"
  match "/blog/:id/:title", :controller => "blogs", :action => "show"
  match "/category/:category", :controller => "blogs", :action => "category_wise"
  match ":controller/:action"


end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  has_many :blogs
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  # GET /contributors
  # GET /contributors.xml
  def index
    @contributors = Contributor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contributors }
    end
  end

  # GET /contributors/1
  # GET /contributors/1.xml
  def show
    @contributor = Contributor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contributor }
    end
  end

  # GET /contributors/new
  # GET /contributors/new.xml
  def new
    @contributor = Contributor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contributor }
    end
  end

  # GET /contributors/1/edit
  def edit
    @contributor = Contributor.find(params[:id])
  end

  # POST /contributors
  # POST /contributors.xml
  def create
    @contributor = Contributor.new(params[:contributor])

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to(@contributor, :notice => 'Contributor was successfully created.') }
        format.xml  { render :xml => @contributor, :status => :created, :location => @contributor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contributors/1
  # PUT /contributors/1.xml
  def update
    @contributor = Contributor.find(params[:id])

    respond_to do |format|
      if @contributor.update_attributes(params[:contributor])
        format.html { redirect_to(@contributor, :notice => 'Contributor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contributors/1
  # DELETE /contributors/1.xml
  def destroy
    @contributor = Contributor.find(params[:id])
    @contributor.destroy

    respond_to do |format|
      format.html { redirect_to(contributors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_form.html.erb
<div class="two-thirds">
    <%= form_for(@contributor) do |f| %>
        <% if @contributor.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@contributor.errors.count, "error") %> prohibited this contributor from being saved:</h2>
                <ul>
                    <% @contributor.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="field">
            <%= f.label :username %><br />
            <%= f.text_field :username %>
        </div>
        <div class="field">
            <%= f.label :email %><br />
            <%= f.text_field :email %>
        </div>
        <div class="actions">
            <%= f.submit %>
        </div>
    <% end %>
</div>

app/views/contributors/edit.html.erb
<div class="two-thirds">
    <h1>Editing contributor</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @contributor %> |
</div>

app/views/contributors/index.html.erb
<div class="two-thirds">
    <h1>Listing contributors</h1>
    <table>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <% @contributors.each do |contributor| %>
            <tr>
                <td><%= contributor.username %></td>
                <td><%= contributor.email %></td>
                <td><%= link_to 'Show', contributor %></td>
                <td><%= link_to 'Edit', edit_contributor_path(contributor) %></td>
                <td><%= link_to 'Destroy', contributor, :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
        <% end %>
    </table>
    <br />
    <%= link_to 'New Contributor', new_contributor_path %>
</div>

app/views/contributors/new.html.erb
<div class="two-thirds">
    <h1>New contributor</h1>
    <%= render 'form' %>
</div>

app/views/contributors/show.html.erb
<div class="two-thirds">
    <p id="notice"><%= notice %></p>
    <p>
        <b>Username:</b>
        <%= @contributor.username %>
    </p>
    <p>
        <b>Email:</b>
        <%= @contributor.email %>
    </p>
    <%= link_to 'Edit', edit_contributor_path(@contributor) %> |
</div>